### ISSUE TITLE
Initial value inconsistency with flatMap and slidingWindow stream

### ISSUE THREAD

**Issue by andpor** [baconjs/bacon.model#22]
This one has been bothering me for a few days now and I am not able to figure it out. 

I have the following trivial Bacon/BaconModel code:

    var t = new Bacon.Model(5);
    t.slidingWindow(2,1).changes().onValue(value => {
      if (value.length == 1)
      	console.log("t : "+value[0]);
      else
      	console.log("t : "+value[1]+","+value[0]);
    });
    t.set(8);
    t.set(2);
    t.set(3);

What this seems to produce is the following stream:

    t : 8,5
    t : 2,8
    t : 3,2

There is no initial value in this stream.

But as soon as I introduce a trivial flatMap into the mix, I start receiving the initial value which is NOT what I want. Please disregard what the sample flatMap does - it is simple yet valid I think for illustration purposes..

    var t = new Bacon.Model(5);
    t.flatMap(value => {return value}).slidingWindow(2,1).changes().onValue(value => {
       if (value.length == 1)
           console.log("t : "+value[0]);
       else
           console.log("t : "+value[1]+","+value[0]);
    });
    t.set(8);
    t.set(2);
    t.set(3);

The output stream becomes:

    t : 5
    t : 8,5
    t : 2,8
    t : 3,2

Please, could someone explain why is addition of flatMap causing the initial value t : 5 to be generated by this chain? Is this as designed or a bug ? If as designed, can you explain why it is generating the initial value output?

[fiddle][1]

  [1]: http://jsfiddle.net/fkuciapa/qkgza5xc/

**Comment by raimohanska** [comment]
Hi, this happens because `flatMap` returns and `EventsStream` and all events in an `EventStream` are of type `Next` and not `Initial`. So the first value 5 is not considered the initial value of the `Property`. It's of course up to speculation whether this is a good thing or a bad thing. See here: http://jsfiddle.net/17eLhzLw/

If you always want to skip the first value of an `Observable`, you can use `.skip(1)` instead of `changes()`.

I hope this helps!

**Comment by andpor** [comment]
This makes sense now. THank you.
